{{ 
    config(
        unique_key='lga_code_2016',
        alias='census_g01_cleaned'
    ) 
}}

select 
    lga_code_2016,
    tot_p_m,
    tot_p_f,
    tot_p_p,
    coalesce(age_0_4_yr_m, 0) as age_0_4_yr_m,
    coalesce(age_0_4_yr_f, 0) as age_0_4_yr_f,
    coalesce(age_0_4_yr_p, 0) as age_0_4_yr_p,
    coalesce(age_5_14_yr_m, 0) as age_5_14_yr_m,
    coalesce(age_5_14_yr_f, 0) as age_5_14_yr_f,
    coalesce(age_5_14_yr_p, 0) as age_5_14_yr_p,
    coalesce(age_15_19_yr_m, 0) as age_15_19_yr_m,
    coalesce(age_15_19_yr_f, 0) as age_15_19_yr_f,
    coalesce(age_15_19_yr_p, 0) as age_15_19_yr_p,
    coalesce(age_20_24_yr_m, 0) as age_20_24_yr_m,
    coalesce(age_20_24_yr_f, 0) as age_20_24_yr_f,
    coalesce(age_20_24_yr_p, 0) as age_20_24_yr_p,
    coalesce(age_25_34_yr_m, 0) as age_25_34_yr_m,
    coalesce(age_25_34_yr_f, 0) as age_25_34_yr_f,
    coalesce(age_25_34_yr_p, 0) as age_25_34_yr_p,
    coalesce(age_35_44_yr_m, 0) as age_35_44_yr_m,
    coalesce(age_35_44_yr_f, 0) as age_35_44_yr_f,
    coalesce(age_35_44_yr_p, 0) as age_35_44_yr_p,
    coalesce(age_45_54_yr_m, 0) as age_45_54_yr_m,
    coalesce(age_45_54_yr_f, 0) as age_45_54_yr_f,
    coalesce(age_45_54_yr_p, 0) as age_45_54_yr_p,
    coalesce(age_55_64_yr_m, 0) as age_55_64_yr_m,
    coalesce(age_55_64_yr_f, 0) as age_55_64_yr_f,
    coalesce(age_55_64_yr_p, 0) as age_55_64_yr_p,
    coalesce(age_65_74_yr_m, 0) as age_65_74_yr_m,
    coalesce(age_65_74_yr_f, 0) as age_65_74_yr_f,
    coalesce(age_65_74_yr_p, 0) as age_65_74_yr_p,
    coalesce(age_75_84_yr_m, 0) as age_75_84_yr_m,
    coalesce(age_75_84_yr_f, 0) as age_75_84_yr_f,
    coalesce(age_75_84_yr_p, 0) as age_75_84_yr_p,
    coalesce(age_85ov_m, 0) as age_85ov_m,
    coalesce(age_85ov_f, 0) as age_85ov_f,
    coalesce(age_85ov_p, 0) as age_85ov_p,
    coalesce(counted_census_night_home_m, 0) as counted_census_night_home_m,
    coalesce(counted_census_night_home_f, 0) as counted_census_night_home_f,
    coalesce(counted_census_night_home_p, 0) as counted_census_night_home_p,
    coalesce(count_census_nt_ewhere_aust_m, 0) as count_census_nt_ewhere_aust_m,
    coalesce(count_census_nt_ewhere_aust_f, 0) as count_census_nt_ewhere_aust_f,
    coalesce(count_census_nt_ewhere_aust_p, 0) as count_census_nt_ewhere_aust_p,
    coalesce(indigenous_psns_aboriginal_m, 0) as indigenous_psns_aboriginal_m,
    coalesce(indigenous_psns_aboriginal_f, 0) as indigenous_psns_aboriginal_f,
    coalesce(indigenous_psns_aboriginal_p, 0) as indigenous_psns_aboriginal_p,
    coalesce(indig_psns_torres_strait_is_m, 0) as indig_psns_torres_strait_is_m,
    coalesce(indig_psns_torres_strait_is_f, 0) as indig_psns_torres_strait_is_f,
    coalesce(indig_psns_torres_strait_is_p, 0) as indig_psns_torres_strait_is_p,
    coalesce(indig_bth_abor_torres_st_is_m, 0) as indig_bth_abor_torres_st_is_m,
    coalesce(indig_bth_abor_torres_st_is_f, 0) as indig_bth_abor_torres_st_is_f,
    coalesce(indig_bth_abor_torres_st_is_p, 0) as indig_bth_abor_torres_st_is_p,
    coalesce(indigenous_p_tot_m, 0) as indigenous_p_tot_m,
    coalesce(indigenous_p_tot_f, 0) as indigenous_p_tot_f,
    coalesce(indigenous_p_tot_p, 0) as indigenous_p_tot_p,
    coalesce(birthplace_australia_m, 0) as birthplace_australia_m,
    coalesce(birthplace_australia_f, 0) as birthplace_australia_f,
    coalesce(birthplace_australia_p, 0) as birthplace_australia_p,
    coalesce(birthplace_elsewhere_m, 0) as birthplace_elsewhere_m,
    coalesce(birthplace_elsewhere_f, 0) as birthplace_elsewhere_f,
    coalesce(birthplace_elsewhere_p, 0) as birthplace_elsewhere_p,
    coalesce(lang_spoken_home_eng_only_m, 0) as lang_spoken_home_eng_only_m,
    coalesce(lang_spoken_home_eng_only_f, 0) as lang_spoken_home_eng_only_f,
    coalesce(lang_spoken_home_eng_only_p, 0) as lang_spoken_home_eng_only_p,
    coalesce(lang_spoken_home_oth_lang_m, 0) as lang_spoken_home_oth_lang_m,
    coalesce(lang_spoken_home_oth_lang_f, 0) as lang_spoken_home_oth_lang_f,
    coalesce(lang_spoken_home_oth_lang_p, 0) as lang_spoken_home_oth_lang_p,
    coalesce(australian_citizen_m, 0) as australian_citizen_m,
    coalesce(australian_citizen_f, 0) as australian_citizen_f,
    coalesce(australian_citizen_p, 0) as australian_citizen_p,
    coalesce(age_psns_att_educ_inst_0_4_m, 0) as age_psns_att_educ_inst_0_4_m,
    coalesce(age_psns_att_educ_inst_0_4_f, 0) as age_psns_att_educ_inst_0_4_f,
    coalesce(age_psns_att_educ_inst_0_4_p, 0) as age_psns_att_educ_inst_0_4_p,
    coalesce(age_psns_att_educ_inst_5_14_m, 0) as age_psns_att_educ_inst_5_14_m,
    coalesce(age_psns_att_educ_inst_5_14_f, 0) as age_psns_att_educ_inst_5_14_f,
    coalesce(age_psns_att_educ_inst_5_14_p, 0) as age_psns_att_educ_inst_5_14_p,
    coalesce(age_psns_att_edu_inst_15_19_m, 0) as age_psns_att_edu_inst_15_19_m,
    coalesce(age_psns_att_edu_inst_15_19_f, 0) as age_psns_att_edu_inst_15_19_f,
    coalesce(age_psns_att_edu_inst_15_19_p, 0) as age_psns_att_edu_inst_15_19_p,
    coalesce(age_psns_att_edu_inst_20_24_m, 0) as age_psns_att_edu_inst_20_24_m,
    coalesce(age_psns_att_edu_inst_20_24_f, 0) as age_psns_att_edu_inst_20_24_f,
    coalesce(age_psns_att_edu_inst_20_24_p, 0) as age_psns_att_edu_inst_20_24_p,
    coalesce(age_psns_att_edu_inst_25_ov_m, 0) as age_psns_att_edu_inst_25_ov_m,
    coalesce(age_psns_att_edu_inst_25_ov_f, 0) as age_psns_att_edu_inst_25_ov_f,
    coalesce(age_psns_att_edu_inst_25_ov_p, 0) as age_psns_att_edu_inst_25_ov_p,
    coalesce(high_yr_schl_comp_yr_12_eq_m, 0) as high_yr_schl_comp_yr_12_eq_m,
    coalesce(high_yr_schl_comp_yr_12_eq_f, 0) as high_yr_schl_comp_yr_12_eq_f,
    coalesce(high_yr_schl_comp_yr_12_eq_p, 0) as high_yr_schl_comp_yr_12_eq_p,
    coalesce(high_yr_schl_comp_yr_11_eq_m, 0) as high_yr_schl_comp_yr_11_eq_m,
    coalesce(high_yr_schl_comp_yr_11_eq_f, 0) as high_yr_schl_comp_yr_11_eq_f,
    coalesce(high_yr_schl_comp_yr_11_eq_p, 0) as high_yr_schl_comp_yr_11_eq_p,
    coalesce(high_yr_schl_comp_yr_10_eq_m, 0) as high_yr_schl_comp_yr_10_eq_m,
    coalesce(high_yr_schl_comp_yr_10_eq_f, 0) as high_yr_schl_comp_yr_10_eq_f,
    coalesce(high_yr_schl_comp_yr_10_eq_p, 0) as high_yr_schl_comp_yr_10_eq_p,
    coalesce(high_yr_schl_comp_yr_9_eq_m, 0) as high_yr_schl_comp_yr_9_eq_m,
    coalesce(high_yr_schl_comp_yr_9_eq_f, 0) as high_yr_schl_comp_yr_9_eq_f,
    coalesce(high_yr_schl_comp_yr_9_eq_p, 0) as high_yr_schl_comp_yr_9_eq_p,
    coalesce(high_yr_schl_comp_yr_8_belw_m, 0) as high_yr_schl_comp_yr_8_belw_m,
    coalesce(high_yr_schl_comp_yr_8_belw_f, 0) as high_yr_schl_comp_yr_8_belw_f,
    coalesce(high_yr_schl_comp_yr_8_belw_p, 0) as high_yr_schl_comp_yr_8_belw_p,
    coalesce(high_yr_schl_comp_d_n_g_sch_m, 0) as high_yr_schl_comp_d_n_g_sch_m,
    coalesce(high_yr_schl_comp_d_n_g_sch_f, 0) as high_yr_schl_comp_d_n_g_sch_f,
    coalesce(high_yr_schl_comp_d_n_g_sch_p, 0) as high_yr_schl_comp_d_n_g_sch_p,
    coalesce(count_psns_occ_priv_dwgs_m, 0) as count_psns_occ_priv_dwgs_m,
    coalesce(count_psns_occ_priv_dwgs_f, 0) as count_psns_occ_priv_dwgs_f,
    coalesce(count_psns_occ_priv_dwgs_p, 0) as count_psns_occ_priv_dwgs_p,
    coalesce(count_persons_other_dwgs_m, 0) as count_persons_other_dwgs_m,
    coalesce(count_persons_other_dwgs_f, 0) as count_persons_other_dwgs_f,
    coalesce(count_persons_other_dwgs_p, 0) as count_persons_other_dwgs_p

from {{ ref('census_g01') }}

